version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:${VERSION:-0.28}
    container_name: openhands-${DATE:-}
    env_file:
      - .env
    ports:
      - "3000:${PORT:-34567}"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: openhands-state
        target: /.openhands-state
      - type: volume
        source: workspace
        target: /workspace
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:${VERSION:-0.28}-nikolaik
      - LOG_ALL_EVENTS=true
      - WORKSPACE_MOUNT_PATH=/openhands/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: always
    stdin_open: true
    tty: true

volumes:
  workspace:
  openhands-state:
